### PR TITLE
Compile to direct executable on Windows x64, Ubuntu x64, and MacOS arm

### PR DESCRIPTION
**Pull request by cassowaree**
Adds compilation with Nuitka, which removes any need for installation. The user can directly download the file and execute it without having Python at all.

Wrote sparse additional documentation. If additional documentation is necessary, I can add more. For example, I can imagine people being confused by antivirus things, etc. because the direct executable versions are a little weird the first time they are run.

### CODE REVIEW

**Comment by cassowaree** [comment]
keeping as draft for now. compilation may need some tweaking due to nuitka updating

**Comment by nythepegasus** [comment]
This looks great! I have been dead in terms of this project, but what all needs done to get this PR merge ready besides me just hitting the funny green button? hehe. 

I do intend to do a lot of repo cleaning here soon, but I definitely want to make sure I'm ready to dive back into all the amazing updates you guys have made.

**Comment by jeffzyliu** [comment]
i may make a new PR to clean a few things up with nuitka versioning and whatnot. will take a look later

**Comment by cassowaree** [comment]
i might take a look at this again and check if there's any changes i need to make to the nuitka version

**Comment by cassowaree** [comment]
looks like there's some new compilation errors that i will have to sort out

**Pull request merged**
