### PR TITLE
workarounds for podman

### PR DESCRIPTION
**Pull request by takov751**
After testing setup on Fedora 40 arm64 I had to add these minor workarounds to ensure compatiblity

### CODE REVIEW

**Comment by stossy11** [comment]
SideJITServer on Asahi Linux when???? (im saying because Asahi Linux is based on fedora lmao)

**Comment by takov751** [comment]
I mean based on thid  oci image is possible to my knowledge.

**Comment by Macleykun** [comment]
> I mean based on thid oci image is possible to my knowledge, just need someone with hardware to test run it

would you like to merge this PR only if we can find someone who happens to run asahi linux?

**Comment by takov751** [comment]
This PR on it's on good enough for merging for folks on any linux distribution. Asahi just a really specific edge case which was not tested.

**Comment by nythepegasus** [comment]
I will merge this as it LGTM.

**Pull request merged**
