### PR TITLE
Linux docker improvements

### PR DESCRIPTION
**Pull request by takov751**
I was able to make this work for now inside docker image user is root, however possible workaround might be adding. Need more testing 
```
setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python\``
```
Anyhow with this multistage approach i was able to shrink down docker image from 600MB to  346MB.

### CODE REVIEW

**Comment by lockieluke** [comment]
This error is still not fixed for some reason:
```
23.27       sslpsk_pmd3/_sslpsk.c:19:10: fatal error: openssl/ssl.h: No such file or directory
23.27          19 | #include <openssl/ssl.h>
23.27             |          ^~~~~~~~~~~~~~~
23.27       compilation terminated.
23.27       error: command '/usr/bin/gcc' failed with exit code 1
23.27       [end of output]
```

**Comment by takov751** [comment]
@lockieluke I would need more context as I have not encountered with issue on either native nor docker build. What is your setup (docker/podman) or just how I would be able to reproduce it. So far what i see that openssl dev library not installed. Are you perhaps cross compiling ?

**Comment by lockieluke** [comment]
I use OrbStack on macOS

**Comment by WesleyBryie** [comment]
> I use OrbStack on macOS

Please try using the docker command line or docker compose.

**Comment by takov751** [comment]
> I use OrbStack on macOS

In case you are on macOS you might not want to use docker. Just python module itself

**Pull request closed without merging**
